obj-m += rn8209_test.o

rn8209_test-objs := rn8209_sample.o \
                    meter_uart.o \
                    rn8209_driver.o \
                    nor_flash_simulator.o \
                    pu_bitmap.o \
                    pu_doublecheck_bitmap.o \
                    pu_mem_pool.o \
                    pu_mem_tracker.o \
                    pu_ndb.o \
                    pu_queue.o \
                    pu_ringbuffer.o \
                    pu_util.o